/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.CuentaControl;
import Controladores.CuentaJpaController;
import Controladores.DetallediarioJpaController;
import Controladores.DiarioJpaController;
import Modelos.Cuenta;
import Modelos.DetalleDiarioTableModel;
import Modelos.Detallediario;
import Modelos.Diario;
import Modelos.DiarioTableModel;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Merii
 */
public class AprobarPartida extends javax.swing.JFrame {
    public DiarioTableModel diarioTModel=new DiarioTableModel();
    public DetalleDiarioTableModel diarioDTModel=new DetalleDiarioTableModel();
    double saldoModificar;

    /**
     * Creates new form AprobarPartida
     */
    public AprobarPartida() {
        initComponents();
        inicializarColumnas();
        consultaInicial();
    }
    
    private void inicializarColumnas(){
        TableColumnModel tDiarioColumnModel=new DefaultTableColumnModel();
        for(int i=0; i<2;i++){
            TableColumn col=new TableColumn(i);
            switch(i){
                case 0:
                    col.setHeaderValue("Código");
                break;
                case 1:
                    col.setHeaderValue("Concepto"); 
            }
            tDiarioColumnModel.addColumn(col);
        }
        tablaDiario.setColumnModel(tDiarioColumnModel);
        
        TableColumnModel tDetalleColumnModel=new DefaultTableColumnModel();
        for(int i=0; i<4;i++){
            TableColumn col=new TableColumn(i);
            switch(i){
                case 0:
                    col.setHeaderValue("Código");
                break;
                case 1:
                    col.setHeaderValue("Nombre");
                break;
                case 2:
                    col.setHeaderValue("Debe");  
                break;
                case 3:
                    col.setHeaderValue("Haber");  
            }
            tDetalleColumnModel.addColumn(col);
        }
        tablaDetalle.setColumnModel(tDetalleColumnModel);
    }
    
    private void consultaInicial(){
        try{
            DiarioJpaController diarioControl=new DiarioJpaController(login.conexion);
            List <Diario> listaDiario=new ArrayList<Diario>(); 
            
            listaDiario=diarioControl.findDiarioEntities();
            for (Diario diario:listaDiario){
                if(diario.getEstadodiario()=='N')//Mostrar sólo los diario No Aprobados.
                    diarioTModel.listaDiario.add(diario);
            }
            tablaDiario.repaint();

        }catch(Exception e){         
        }
    }
    private void llenarTablaDetalle(){
        diarioDTModel.listaDetalleDiario.clear();
        if(!txtCodigo.getText().isEmpty()){
            try{
                DetallediarioJpaController detalleControl=new DetallediarioJpaController(login.conexion);
                List <Detallediario> listaDetalleDiario=new ArrayList<Detallediario>(); 
            
                listaDetalleDiario=detalleControl.findDetallediarioEntities();
                for (Detallediario detalle:listaDetalleDiario){
                    if(detalle.getIdregistro().getIdregistro()==Integer.parseInt(txtCodigo.getText()))
                        diarioDTModel.listaDetalleDiario.add(detalle);
                }
            }catch(Exception e){
            }
        }
        tablaDetalle.updateUI();
    }
    private void actualizarVista(){
        txtCodigo.setText("");
        diarioTModel.listaDiario.clear();
        consultaInicial();
        llenarTablaDetalle();
        tablaDiario.updateUI();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDiario = new javax.swing.JTable();
        btnAprobar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalle = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Aprobacion de Partidas");

        tablaDiario.setModel(diarioTModel);
        tablaDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDiarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDiario);

        btnAprobar.setText("Aprobar");
        btnAprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprobarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(btnAprobar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnAprobar))
                .addContainerGap())
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tablaDetalle.setModel(diarioDTModel);
        jScrollPane2.setViewportView(tablaDetalle);

        jLabel2.setText("Numero de Partida:");

        txtCodigo.setEditable(false);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        PrincipalContabilidad prin = new PrincipalContabilidad();
        prin.setVisible(true);
        prin.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(!txtCodigo.getText().isEmpty()){
            try{
                DiarioJpaController diarioControl=new DiarioJpaController(login.conexion);
                Diario diario=diarioControl.findDiario(Integer.parseInt(txtCodigo.getText()));
                DetallediarioJpaController detalleControl=new DetallediarioJpaController(login.conexion);
                for (Detallediario detalle:diarioDTModel.listaDetalleDiario){
                    if(detalle.getIdregistro().getIdregistro()==Integer.parseInt(txtCodigo.getText()))
                        detalleControl.destroy(detalle.getIddetalle());
                }
                diarioControl.destroy(Integer.parseInt(txtCodigo.getText()));
                actualizarVista();
                JOptionPane.showMessageDialog(this,"Diario eliminado con exito!");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error al eliminar el Diario!");
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Seleccione el Diario que desea eliminar!");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaDiarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDiarioMouseClicked
        // TODO add your handling code here:
        int clics = evt.getClickCount();
        int row = tablaDiario.rowAtPoint(evt.getPoint());
        if (clics == 2) {
            String codDiario=tablaDiario.getValueAt(row, 0).toString();
            txtCodigo.setText(codDiario);
            llenarTablaDetalle();   
        }
    }//GEN-LAST:event_tablaDiarioMouseClicked

    private void btnAprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprobarActionPerformed
        // TODO add your handling code here:
        if(!txtCodigo.getText().isEmpty()){
            try{
                DiarioJpaController diarioControl=new DiarioJpaController(login.conexion);
                Diario diario=diarioControl.findDiario(Integer.parseInt(txtCodigo.getText()));
                diario.setEstadodiario('A');
                diarioControl.edit(diario);
                //Actualizar saldos de las cuentas
                DetallediarioJpaController detalleControl=new DetallediarioJpaController(login.conexion);
                CuentaJpaController cuentaControl=new CuentaJpaController(login.conexion);
                for(Detallediario detalle : diarioDTModel.listaDetalleDiario){
                    if(detalle.getIdregistro().getIdregistro()==diario.getIdregistro()){
                        Cuenta cuenta=cuentaControl.findCuenta(detalle.getCodcuenta().getCodcuenta());
                        saldoModificar=detalle.getDebe().doubleValue() - detalle.getHaber().doubleValue();
                        cuenta.setSaldocuenta(BigDecimal.valueOf(cuenta.getSaldocuenta().doubleValue() + saldoModificar));
                        cuentaControl.edit(cuenta);
                        CuentaControl.actualizarSaldoCuentasPadre(cuenta, saldoModificar);
                    } 
                }
                actualizarVista();
                JOptionPane.showMessageDialog(this,"Diario aprobado con exito!");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error al aprobar el Diario!");
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Seleccione el Diario que desea aprobar!");
        }
    }//GEN-LAST:event_btnAprobarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AprobarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AprobarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AprobarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AprobarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AprobarPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tablaDetalle;
    private javax.swing.JTable tablaDiario;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
