/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.CuentaJpaController;
import Controladores.DiarioControl;
import Modelos.Detallediario;
import java.math.BigDecimal;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Merii
 */
public class PlanillaGenerada extends javax.swing.JFrame {

    /**
     * Creates new form PlanillaGenerada
     * @param totalAdmin
     * @param totalOtros
     * @param totalAfp
     * @param totalIsss
     * @param totalRenta
     */
    public PlanillaGenerada(BigDecimal totalAdmin, BigDecimal totalOtros, BigDecimal totalAfp, BigDecimal totalIsss, BigDecimal totalRenta) {
        initComponents();
        
        jTable1.setValueAt(totalAdmin, 0, 2);
        jTable1.setValueAt(BigDecimal.ZERO, 0, 3);
        jTable1.setValueAt(totalOtros, 1, 2);
        jTable1.setValueAt(BigDecimal.ZERO, 1, 3);
        jTable1.setValueAt(totalIsss, 3, 3);
        jTable1.setValueAt(BigDecimal.ZERO, 3, 2);
        jTable1.setValueAt(totalAfp, 4, 3);
        jTable1.setValueAt(BigDecimal.ZERO, 4, 2);
        jTable1.setValueAt(totalRenta, 5, 3);
        jTable1.setValueAt(BigDecimal.ZERO, 5, 2);
        BigDecimal bancos = totalAdmin.add(totalOtros).subtract(totalIsss).subtract(totalAfp).subtract(totalRenta);
        jTable1.setValueAt(bancos, 2, 3);
        jTable1.setValueAt(BigDecimal.ZERO, 2, 2);
        jTable1.setEnabled(false);
        
        
    }

    private PlanillaGenerada() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Partida de Pago de Salarios");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"430101", "Sueldos y Salarios", null, null},
                {"420101", "Sueldos y Salarios", null, null},
                {"110103", "Efectivo en Bancos", null, null},
                {"420105", "Cuenta Patronal ISSS", null, null},
                {"420106", "Cuenta Patronal AFP", null, null},
                {"21050103", "Pago a Cuenta e ISR x Pagar", null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Debe ", "Haber"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fecha");

        jLabel3.setText("Concepto");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Pago de Salarios ");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(jButton1)
                                .addGap(236, 236, 236)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CuentaJpaController cuentaControl=new CuentaJpaController(login.conexion);
        List<Detallediario> detalles = new ArrayList<Detallediario>();
        
        for (int i = 0; i < 6; i++) {
            Detallediario detalle = new Detallediario();
            String codCuenta = (String)jTable1.getValueAt(i, 0);
            detalle.setCodcuenta(cuentaControl.findCuenta(codCuenta));
            BigDecimal debe = (BigDecimal)jTable1.getValueAt(i, 2);
            detalle.setDebe(debe);
            BigDecimal haber = (BigDecimal)jTable1.getValueAt(i, 3);
            detalle.setHaber(haber);
            detalles.add(detalle);
        }
        
                if(DiarioControl.validarDetallesDiarios(detalles)){
                if(DiarioControl.validarPartidaDoble(detalles)){
                    if(!jTextArea1.getText().isEmpty()){
                        DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                        try{
                            Date fecha = format.parse(jTextField1.getText());
                            if(DiarioControl.nuevoDiario(detalles, fecha, jTextArea1.getText())){
                                JOptionPane.showMessageDialog(this, "Creación del Diario con éxito");
                                jTextArea1.setText("");
                                detalles.clear();
                                DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
                                int rows = model.getRowCount(); 
                                for(int i = rows - 1; i >=0; i--)
                                {
                                    model.removeRow(i); 
                                }
                                jTable1.setModel(model);
                            }else{
                                JOptionPane.showMessageDialog(this, "Error en la creación del diario!");
                            }
                        }catch(Exception e){
                        JOptionPane.showMessageDialog(this, "Error en los datos de la fecha, recordar que el formato de la fecha es dd/mm/aaaa");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Por favor especifique el Concepto del Diario, antes de Guardarlo.");
                    }
                
                }else{
                    JOptionPane.showMessageDialog(this, "No se cumple Partida Doble, revisar datos en transacciones.");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Error en las transacciones. Recuerde que no dejar el debe y el haber de alguna transaccion a 0.0");
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Planilla plan = new Planilla();
        plan.setVisible(true);
        plan.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlanillaGenerada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlanillaGenerada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlanillaGenerada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlanillaGenerada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlanillaGenerada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
