/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.BaseprorrateoJpaController;
import Controladores.CentrodecostoJpaController;
import Modelos.Baseprorrateo;
import Modelos.Centrodecosto;
import Modelos.Cuenta;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import javax.swing.table.DefaultTableModel; 

/**
 *
 * @author Merii
 */
public class Prorrateo extends javax.swing.JFrame {
    BaseprorrateoJpaController baseCtrl = new BaseprorrateoJpaController(login.conexion);
    CentrodecostoJpaController costoCtrl = new CentrodecostoJpaController(login.conexion);
    List<Baseprorrateo> bases = new ArrayList<>();//baseCtrl.findBaseprorrateoEntities();
    List<Centrodecosto> centros = costoCtrl.findCentrodecostoEntities();
    DefaultTableModel proTModel = new DefaultTableModel();
    List<String> nomBases = new ArrayList<>();
    List<BigDecimal[]> coef = new ArrayList<>();
    List<BigDecimal[]> datos = new ArrayList<>();
    EntityManager entity = login.conexion.createEntityManager(); 
    /**
     * Creates new form Prorrateo
     */
    public Prorrateo() {
        initComponents();
                    //Asignando las columnas
        jTable1.setModel(proTModel);    
        proTModel.addColumn("Base Prorrateo");
        proTModel.addColumn("Total Base");
        for(Centrodecosto c:centros){
               proTModel.addColumn(c.getNomcentro());
           }
        Object [] row = new Object[centros.size()+2];    
        nomBases = entity.createNativeQuery("select distinct nombase from baseprorrateo natural join cuenta").getResultList();
        for(String b:nomBases){
            row[0] = b;
            Baseprorrateo base = baseCtrl.findBaseprorrateoByName(b);
            row[1] = base.getTotalbase();
            bases.add(base);
            proTModel.addRow(row);
        }
        
           /*EntityManager entity = login.conexion.createEntityManager(); 
           List<BigDecimal> numeros = entity.createNativeQuery("select totalcosto from centrodecosto natural join prorrateo order by idbase, nomcentro;").getResultList();
           List<String> columnas = entity.createNativeQuery("select distinct nomcentro from centrodecosto order by nomcentro;").getResultList();*/
           
          /*Object [] row = new Object[columnas.size()+2];
          int j=0;
          
          /*for(Baseprorrateo b:baseCtrl.findBaseprorrateoEntities()){
              BigDecimal[] fila = new BigDecimal[columnas.size()];
              row[0] = b.getNombase();
              row[1] = b.getTotalbase();
              for (int i = 0; i < columnas.size(); i++) {
                  row[i+2] = numeros.get(i+(columnas.size()*j));
                  BigDecimal p = numeros.get(i+(columnas.size()*j));
                  BigDecimal q = b.getTotalbase();
                  fila[i] = p.divide(q,2,BigDecimal.ROUND_HALF_UP);
              }
              j++;
              datos.add(fila);
              proTModel.addRow(row);
          }*/
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Base de Prorrateo", "Total de Base", "Departamento A", "Departamento B", "Departamento C"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Contabilidad de Costos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setText("Prorratear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Gestionar Bases y Costos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1)
                        .addGap(21, 21, 21)))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Generar pdf de prorrateo
     
        for (int i = 0; i < nomBases.size(); i++) {
            Baseprorrateo baseActual = bases.get(i);
            //Calculando los procentajes para el prorrateo
            BigDecimal[] coefila = new BigDecimal[centros.size()];
            for (int j = 0; j < coefila.length; j++) {
                String temp = (String)jTable1.getValueAt(i, j+2);
                BigDecimal p = BigDecimal.ZERO;
                if(temp!=null){p = new BigDecimal(temp.replace(",", ""));}                
                BigDecimal q = baseActual.getTotalbase();
                coefila[j] = p.divide(q,2,BigDecimal.ROUND_HALF_UP);
            }
            coef.add(coefila); //Se añaden a datos para ser mostrados luego
            
            //Multiplicando los totales de cada cuenta para prorratear           
            //List<Cuenta> cuentas = baseActual.getCuentaList(); //Esto puede ser cambiado por una Query SQL que me devuelva los totales cuando la base sea igual al nombre        
            
            List<BigDecimal> cuentas = entity.createNativeQuery("select saldocuenta from cuenta where idbase = "+baseActual.getIdbase()+";").getResultList();
            for(BigDecimal c:cuentas){
                BigDecimal[] prorra = new BigDecimal[centros.size()];
                for (int j = 0; j < prorra.length; j++) {
                    prorra[j] = coefila[j].multiply(c/*.getSaldocuenta()*/);
                }
                datos.add(prorra);
            }
            //Fin prorrateo
            
        }
        System.out.println("Prorrateo");
        for(BigDecimal[] c : datos){
            System.out.println("\nFila");
            for (int i = 0; i < c.length; i++) {
                System.out.println(c[i]);
            }
            System.out.println("Limit");
        }

        //Coeficientes en COEF
        //Resultado del prorrateo en DATOS
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        BasesyCentros bc = new BasesyCentros();
        bc.setVisible(true);
        bc.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PrincipalContabilidad con = new PrincipalContabilidad();
        con.setVisible(true);
        con.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prorrateo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prorrateo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prorrateo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prorrateo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prorrateo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
